version: '3'
services:
  rails:
    image: ruby:3.1.3
    volumes:
      - ./rails/nginx-unicorn-rails-test:/app
    working_dir: /app
    command: bash start.sh
    ports:
      - 8080:8080
  nginx:
    image: nginx:1.23.2
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  squid:
    image: ubuntu/squid:5.2-22.04_beta
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
    ports:
      - 3128:3128
  http-client:
    image: golang:1.19.3-bullseye
    volumes:
      - ./http-client/scripts:/scripts
    working_dir: /scripts
    tty: true