version: '3'
services:
  rails:
    image: ruby:3.1.3
    volumes:
      - ./rails/nginx-unicorn-rails-test:/app
    working_dir: /app
    command: bash start.sh
    ports:
      - 8080:8080
  nginx:
    image: nginx:1.23.2
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  toxiproxy:
    image: shopify/toxiproxy:2.1.4
    volumes:
      - ./toxiproxy/setting_proxy.sh:/setting_proxy:ro
    ports:
      - 8888:8888
