version: '3'
services:
  rails:
    build:
      context: rails
    volumes:
      - ./rails/nginx-unicorn-rails-test:/app
    working_dir: /app
    command: bash start.sh
    ports:
      - 8080:8080
  nginx:
    build:
      context: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
  